---
title: "R og RStudio"
author: ""
date: "`r format(Sys.Date(), format = '%d.%m.%Y')`"
output: 
  xaringan::moon_reader:
    lib_dir: libs
    css: ["ntnu_slides.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

class: inverse, middle, right

### "Jeg vil i fullt alvor hevde at det gjøres en hel del skade i vår tid ved troen på det moralsk høyverdige ved ARBEID." 
### - Bertrand Russell, **Til lediggangens lov**

---

class: middle, center

### Rrrrask gjennomgang av R

---

# Bestanddeler


--

.pull-left[
### Fakta om R
{{content}}
]
--
1. Alt har et **navn**
{{content}}
--
1. Alt er et **objekt**
{{content}}
--
1. Du gjør ting med **funksjoner**
{{content}}
--
1. Funksjoner kommer i **pakker**

--

.pull-right[
### Eksempel
{{content}}
]

--
1. **kursholder** <- "Henrik" `r kursholder <- "Henrik"`
{{content}}
--
1. **kursholder**:{{content}}
--
 [1] "Henrik"
{{content}}
--
1. *nchar*(**kursholder**):{{content}}
--
`r nchar(kursholder)`
{{content}}
--
<br>
<br>
1. *library*(**tidyverse**)

---

class: center, middle

# Objekter

---




---

class: center, middle

# Funksjoner

Funksjoner er det som gjør ting i R, og de fungerer alle på samme måte: de tar et objekt, gjør noe med det, og leverer fra seg et objekt. 

---



Alle funksjoner har samme form:{{content}}
--

--


---

# Pakker

Samlinger av funksjoner

---

class: inverse, center, middle

### RStudio

---

# Et integrert utviklermiljø

---

